services:

  node:
    image: wodby/node:18-dev-1.9.0
    container_name: "crs4_node"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ../../docs/04-blocks-theming:/var/www/public
    command: sh -c 'yarn install && yarn run start'
